version: '3.6'
services:
  web:
    build: .
    image: juliashub/pizza-express:${TAG:-latest}
    ports:
    - "8081:3000"
    links:
    - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  redis:
    image: redis:latest
volumes:
  logvolume01: {}