replicaCount: 1
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext: {}
securityContext: {}

image:
  repository: idevopsiointernal/pizzaexpress
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 80
  app_port: 3000

persistence:
  enabled: true
  size: 1250Gi
  accessMode: ReadWriteOnce

resources:
  requests:
    cpu: 0.5
    memory: 1Gi
  limits:
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

strategyType: Recreate
nodeSelector: {}
tolerations: []
affinity: {}
