apiVersion: v1
kind: Service
metadata:
  name: {{ include "pizzaexpress.fullname" . }}
  labels:
    {{- include "pizzaexpress.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.app_port }}
      protocol: TCP
      name: http
  selector:
    {{- include "pizzaexpress.selectorLabels" . | nindent 4 }}
